-- Popula list_placements com as posicoes de albuns nas listas da Q Magazine (2006)
-- e da Consequence (2022), gerado a partir de q-magazine-100-greatest-albums.md e
-- consequence-100-greatest-albums.md na raiz do projeto.

insert into list_placements (list_slug, list_name, position, artist_name, album_title, normalized_artist, normalized_title)
values
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 1, 'Radiohead', 'OK Computer', 'radiohead', 'ok computer'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 2, 'Radiohead', 'The Bends', 'radiohead', 'the bends'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 3, 'Nirvana', 'Nevermind', 'nirvana', 'nevermind'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 4, 'The Beatles', 'Revolver', 'the beatles', 'revolver'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 5, 'Oasis', 'Definitely Maybe', 'oasis', 'definitely maybe'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 6, 'The Stone Roses', 'The Stone Roses', 'the stone roses', 'the stone roses'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 7, 'R.E.M.', 'Automatic for the People', 'r e m', 'automatic for the people'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 8, 'Oasis', '(What''s the Story) Morning Glory?', 'oasis', 'what s the story morning glory'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 9, 'U2', 'Achtung Baby', 'u2', 'achtung baby'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 10, 'Radiohead', 'Kid A', 'radiohead', 'kid a'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 11, 'U2', 'The Joshua Tree', 'u2', 'the joshua tree'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 12, 'The Smiths', 'The Queen Is Dead', 'the smiths', 'the queen is dead'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 13, 'Jeff Buckley', 'Grace', 'jeff buckley', 'grace'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 14, 'The Beatles', 'Abbey Road', 'the beatles', 'abbey road'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 15, 'Pink Floyd', 'Dark Side of the Moon', 'pink floyd', 'dark side of the moon'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 16, 'Verve', 'Urban Hymns', 'verve', 'urban hymns'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 17, 'The Beatles', 'The Beatles (The White Album)', 'the beatles', 'the beatles the white album'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 18, 'The Beach Boys', 'Pet Sounds', 'the beach boys', 'pet sounds'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 19, 'The Beatles', 'Sgt. Pepper''s Lonely Hearts Club Band', 'the beatles', 'sgt pepper s lonely hearts club band'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 20, 'The Clash', 'London Calling', 'the clash', 'london calling'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 21, 'Led Zeppelin', 'Led Zeppelin IV', 'led zeppelin', 'led zeppelin iv'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 22, 'Nirvana', 'In Utero', 'nirvana', 'in utero'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 23, 'Bob Dylan', 'Blood on the Tracks', 'bob dylan', 'blood on the tracks'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 24, 'Guns N'' Roses', 'Appetite for Destruction', 'guns n roses', 'appetite for destruction'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 25, 'Coldplay', 'A Rush of Blood to the Head', 'coldplay', 'a rush of blood to the head'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 26, 'The Strokes', 'Is This It', 'the strokes', 'is this it'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 27, 'Pink Floyd', 'The Wall', 'pink floyd', 'the wall'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 28, 'Sex Pistols', 'Never Mind the Bollocks, Here''s the Sex Pistols', 'sex pistols', 'never mind the bollocks here s the sex pistols'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 29, 'The Beatles', 'Rubber Soul', 'the beatles', 'rubber soul'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 30, 'Pink Floyd', 'Wish You Were Here', 'pink floyd', 'wish you were here'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 31, 'Red Hot Chili Peppers', 'Californication', 'red hot chili peppers', 'californication'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 32, 'Marvin Gaye', 'What''s Going On', 'marvin gaye', 'what s going on'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 33, 'Madonna', 'Ray of Light', 'madonna', 'ray of light'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 34, 'The Rolling Stones', 'Exile on Main Street', 'the rolling stones', 'exile on main street'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 35, 'Blur', 'Parklife', 'blur', 'parklife'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 36, 'Bob Dylan', 'Blonde on Blonde', 'bob dylan', 'blonde on blonde'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 37, 'R.E.M.', 'Out of Time', 'r e m', 'out of time'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 38, 'Jimi Hendrix', 'Electric Ladyland', 'jimi hendrix', 'electric ladyland'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 39, 'Primal Scream', 'Screamadelica', 'primal scream', 'screamadelica'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 40, 'Coldplay', 'Parachutes', 'coldplay', 'parachutes'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 41, 'David Bowie', 'The Rise and Fall of Ziggy Stardust and the Spiders from Mars', 'david bowie', 'the rise and fall of ziggy stardust and the spiders from mars'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 42, 'The Velvet Underground', 'The Velvet Underground & Nico', 'the velvet underground', 'the velvet underground nico'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 43, 'Pixies', 'Doolittle', 'pixies', 'doolittle'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 44, 'Joy Division', 'Closer', 'joy division', 'closer'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 45, 'Bob Dylan', 'Highway 61 Revisited', 'bob dylan', 'highway 61 revisited'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 46, 'David Bowie', 'Hunky Dory', 'david bowie', 'hunky dory'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 47, 'Van Morrison', 'Astral Weeks', 'van morrison', 'astral weeks'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 48, 'The Rolling Stones', 'Sticky Fingers', 'the rolling stones', 'sticky fingers'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 49, 'R.E.M.', 'Document', 'r e m', 'document'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 50, 'Love', 'Forever Changes', 'love', 'forever changes'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 51, 'The Who', 'Who''s Next', 'the who', 'who s next'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 52, 'Nirvana', 'Unplugged in New York', 'nirvana', 'unplugged in new york'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 53, 'U2', 'All That You Can''t Leave Behind', 'u2', 'all that you can t leave behind'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 54, 'Smashing Pumpkins', 'Siamese Dream', 'smashing pumpkins', 'siamese dream'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 55, 'Portishead', 'Dummy', 'portishead', 'dummy'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 56, 'Moby', 'Play', 'moby', 'play'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 57, 'Led Zeppelin', 'Physical Graffiti', 'led zeppelin', 'physical graffiti'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 58, 'Michael Jackson', 'Thriller', 'michael jackson', 'thriller'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 59, 'Pearl Jam', 'Ten', 'pearl jam', 'ten'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 60, 'Radiohead', 'Amnesiac', 'radiohead', 'amnesiac'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 61, 'Beck', 'Odelay', 'beck', 'odelay'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 62, 'Kate Bush', 'Hounds of Love', 'kate bush', 'hounds of love'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 63, 'Jimi Hendrix', 'Are You Experienced?', 'jimi hendrix', 'are you experienced'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 64, 'The Rolling Stones', 'Let It Bleed', 'the rolling stones', 'let it bleed'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 65, 'Massive Attack', 'Blue Lines', 'massive attack', 'blue lines'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 66, 'White Stripes', 'White Blood Cells', 'white stripes', 'white blood cells'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 67, 'David Gray', 'White Ladder', 'david gray', 'white ladder'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 68, 'Fleetwood Mac', 'Rumours', 'fleetwood mac', 'rumours'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 69, 'Manic Street Preachers', 'The Holy Bible', 'manic street preachers', 'the holy bible'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 70, 'Travis', 'The Man Who', 'travis', 'the man who'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 71, 'Rage Against the Machine', 'Rage Against the Machine', 'rage against the machine', 'rage against the machine'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 72, 'Miles Davis', 'Kind of Blue', 'miles davis', 'kind of blue'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 73, 'Alanis Morissette', 'Jagged Little Pill', 'alanis morissette', 'jagged little pill'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 74, 'Muse', 'Origin of Symmetry', 'muse', 'origin of symmetry'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 75, 'The Doors', 'The Doors', 'the doors', 'the doors'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 76, 'Johnny Cash', 'American III: Solitary Man', 'johnny cash', 'american iii solitary man'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 77, 'The Clash', 'The Clash', 'the clash', 'the clash'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 78, 'AC/DC', 'Back in Black', 'ac dc', 'back in black'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 79, 'Jam', 'Setting Sons', 'jam', 'setting sons'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 80, 'David Bowie', 'Low', 'david bowie', 'low'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 81, 'Stereophonics', 'Word Gets Around', 'stereophonics', 'word gets around'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 82, 'Bruce Springsteen', 'Born to Run', 'bruce springsteen', 'born to run'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 83, 'Paul Weller', 'Stanley Road', 'paul weller', 'stanley road'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 84, 'Stevie Wonder', 'Songs in the Key of Life', 'stevie wonder', 'songs in the key of life'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 85, 'Pulp', 'Different Class', 'pulp', 'different class'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 86, 'Eminem', 'The Marshall Mathers LP', 'eminem', 'the marshall mathers lp'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 87, 'PJ Harvey', 'Stories from the City, Stories from the Sea', 'pj harvey', 'stories from the city stories from the sea'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 88, 'Neil Young', 'After the Goldrush', 'neil young', 'after the goldrush'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 89, 'Morrissey', 'Vauxhall and I', 'morrissey', 'vauxhall and i'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 90, 'Cure', 'Disintegration', 'cure', 'disintegration'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 91, 'Public Enemy', 'It Takes a Nation of Millions to Hold Us Back', 'public enemy', 'it takes a nation of millions to hold us back'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 92, 'Manic Street Preachers', 'Everything Must Go', 'manic street preachers', 'everything must go'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 93, 'Bob Marley and the Wailers', 'Exodus', 'bob marley and the wailers', 'exodus'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 94, 'Prince and the Revolution', 'Purple Rain', 'prince and the revolution', 'purple rain'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 95, 'Iggy Pop & The Stooges', 'Raw Power', 'iggy pop the stooges', 'raw power'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 96, 'Kraftwerk', 'The Man Machine', 'kraftwerk', 'the man machine'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 97, 'Lou Reed', 'Transformer', 'lou reed', 'transformer'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 98, 'Beastie Boys', 'Paul''s Boutique', 'beastie boys', 'paul s boutique'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 99, 'Tom Waits', 'Rain Dogs', 'tom waits', 'rain dogs'),
('q-magazine-100', 'Q Magazine''s 100 Greatest Albums Ever', 100, 'Wilco', 'Yankee Hotel Foxtrot', 'wilco', 'yankee hotel foxtrot'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 1, 'Prince And The Revolution', 'Purple Rain', 'prince and the revolution', 'purple rain'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 2, 'Fleetwood Mac', 'Rumours', 'fleetwood mac', 'rumours'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 3, 'The Beatles', 'Abbey Road', 'the beatles', 'abbey road'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 4, 'The Clash', 'London Calling', 'the clash', 'london calling'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 5, 'Joni Mitchell', 'Blue', 'joni mitchell', 'blue'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 6, 'The Beach Boys', 'Pet Sounds', 'the beach boys', 'pet sounds'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 7, 'Kendrick Lamar', 'To Pimp A Butterfly', 'kendrick lamar', 'to pimp a butterfly'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 8, 'Radiohead', 'OK Computer', 'radiohead', 'ok computer'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 9, 'Marvin Gaye', 'What''s Going On', 'marvin gaye', 'what s going on'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 10, 'Nirvana', 'Nevermind', 'nirvana', 'nevermind'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 11, 'Lauryn Hill', 'The Miseducation Of Lauryn Hill', 'lauryn hill', 'the miseducation of lauryn hill'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 12, 'Bob Dylan', 'Blonde On Blonde', 'bob dylan', 'blonde on blonde'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 13, 'The Velvet Underground & Nico', 'The Velvet Underground & Nico', 'the velvet underground nico', 'the velvet underground nico'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 14, 'The Beatles', 'Sgt. Pepper''s Lonely Hearts Club Band', 'the beatles', 'sgt pepper s lonely hearts club band'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 15, 'David Bowie', 'The Rise And Fall Of Ziggy Stardust And The Spiders From Mars', 'david bowie', 'the rise and fall of ziggy stardust and the spiders from mars'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 16, 'Bruce Springsteen', 'Born To Run', 'bruce springsteen', 'born to run'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 17, 'Patti Smith', 'Horses', 'patti smith', 'horses'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 18, 'Beyoncé', 'Lemonade', 'beyonce', 'lemonade'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 19, 'Talking Heads', 'Remain In Light', 'talking heads', 'remain in light'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 20, 'Kate Bush', 'Hounds Of Love', 'kate bush', 'hounds of love'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 21, 'Led Zeppelin', 'Untitled (Led Zeppelin IV)', 'led zeppelin', 'untitled led zeppelin iv'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 22, 'Stevie Wonder', 'Songs In The Key Of Life', 'stevie wonder', 'songs in the key of life'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 23, 'The Rolling Stones', 'Let It Bleed', 'the rolling stones', 'let it bleed'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 24, 'Black Sabbath', 'Paranoid', 'black sabbath', 'paranoid'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 25, 'Public Enemy', 'It Takes A Nation Of Millions To Hold Us Back', 'public enemy', 'it takes a nation of millions to hold us back'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 26, 'Ramones', 'Ramones', 'ramones', 'ramones'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 27, 'Michael Jackson', 'Thriller', 'michael jackson', 'thriller'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 28, 'Missy Elliott', 'Supa Dupa Fly', 'missy elliott', 'supa dupa fly'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 29, 'Pink Floyd', 'The Dark Side Of The Moon', 'pink floyd', 'the dark side of the moon'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 30, 'Kanye West', 'My Beautiful Dark Twisted Fantasy', 'kanye west', 'my beautiful dark twisted fantasy'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 31, 'Metallica', 'Master Of Puppets', 'metallica', 'master of puppets'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 32, 'The Beatles', 'The Beatles (The White Album)', 'the beatles', 'the beatles the white album'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 33, 'Rage Against The Machine', 'Rage Against The Machine', 'rage against the machine', 'rage against the machine'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 34, 'Wu-Tang Clan', 'Enter The Wu-Tang (36 Chambers)', 'wu tang clan', 'enter the wu tang 36 chambers'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 35, 'Neil Young', 'After The Gold Rush', 'neil young', 'after the gold rush'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 36, 'Fiona Apple', 'The Idler Wheel Is Wiser Than The Driver Of The Screw And Whipping Cords Will Serve You More Than Ropes Will Ever Do', 'fiona apple', 'the idler wheel is wiser than the driver of the screw and whipping cords will serve you more than ropes will ever do'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 37, 'OutKast', 'Stankonia', 'outkast', 'stankonia'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 38, 'Paul Simon', 'Graceland', 'paul simon', 'graceland'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 39, 'Taylor Swift', '1989', 'taylor swift', '1989'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 40, 'Pixies', 'Doolittle', 'pixies', 'doolittle'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 41, 'Jay-Z', 'Reasonable Doubt', 'jay z', 'reasonable doubt'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 42, 'AC/DC', 'Back In Black', 'ac dc', 'back in black'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 43, 'Bob Dylan', 'Blood On The Tracks', 'bob dylan', 'blood on the tracks'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 44, 'Miles Davis', 'Kind Of Blue', 'miles davis', 'kind of blue'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 45, 'Lady Gaga', 'The Fame Monster', 'lady gaga', 'the fame monster'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 46, 'Nine Inch Nails', 'The Downward Spiral', 'nine inch nails', 'the downward spiral'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 47, 'Van Morrison', 'Astral Weeks', 'van morrison', 'astral weeks'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 48, 'A Tribe Called Quest', 'The Low End Theory', 'a tribe called quest', 'the low end theory'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 49, 'Guns N'' Roses', 'Appetite For Destruction', 'guns n roses', 'appetite for destruction'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 50, 'Iggy And The Stooges', 'Raw Power', 'iggy and the stooges', 'raw power'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 51, 'Johnny Cash', 'At Folsom Prison', 'johnny cash', 'at folsom prison'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 52, 'The Strokes', 'Is This It', 'the strokes', 'is this it'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 53, 'Dr. Dre', '2001', 'dr dre', '2001'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 54, 'Joy Division', 'Unknown Pleasures', 'joy division', 'unknown pleasures'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 55, 'Sly & The Family Stone', 'There''s A Riot Goin'' On', 'sly the family stone', 'there s a riot goin on'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 56, 'David Bowie', 'Hunky Dory', 'david bowie', 'hunky dory'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 57, 'The Band', 'Music From Big Pink', 'the band', 'music from big pink'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 58, 'Nina Simone', 'I Put A Spell On You', 'nina simone', 'i put a spell on you'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 59, 'Nas', 'Illmatic', 'nas', 'illmatic'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 60, 'Amy Winehouse', 'Back To Black', 'amy winehouse', 'back to black'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 61, 'The Rolling Stones', 'Exile On Main St.', 'the rolling stones', 'exile on main st'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 62, 'Madvillain', 'Madvillainy', 'madvillain', 'madvillainy'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 63, 'Tom Waits', 'Rain Dogs', 'tom waits', 'rain dogs'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 64, 'The Cure', 'Disintegration', 'the cure', 'disintegration'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 65, 'Leonard Cohen', 'Songs Of Leonard Cohen', 'leonard cohen', 'songs of leonard cohen'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 66, 'Madonna', 'Like A Prayer', 'madonna', 'like a prayer'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 67, 'Radiohead', 'In Rainbows', 'radiohead', 'in rainbows'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 68, 'Frank Ocean', 'Channel Orange', 'frank ocean', 'channel orange'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 69, 'Beastie Boys', 'Paul''s Boutique', 'beastie boys', 'paul s boutique'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 70, 'Sonic Youth', 'Daydream Nation', 'sonic youth', 'daydream nation'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 71, 'U2', 'The Joshua Tree', 'u2', 'the joshua tree'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 72, 'My Bloody Valentine', 'Loveless', 'my bloody valentine', 'loveless'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 73, 'Parliament', 'Mothership Connection', 'parliament', 'mothership connection'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 74, 'Bob Dylan', 'Highway 61 Revisited', 'bob dylan', 'highway 61 revisited'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 75, 'Janelle Monáe', 'Dirty Computer', 'janelle monae', 'dirty computer'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 76, 'The Smiths', 'The Queen Is Dead', 'the smiths', 'the queen is dead'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 77, 'Jay-Z', 'The Black Album', 'jay z', 'the black album'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 78, 'Billy Joel', 'The Stranger', 'billy joel', 'the stranger'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 79, 'The Police', 'Synchronicity', 'the police', 'synchronicity'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 80, 'Erykah Badu', 'Baduizm', 'erykah badu', 'baduizm'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 81, 'Adele', '21', 'adele', '21'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 82, 'Peter Gabriel', 'So', 'peter gabriel', 'so'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 83, 'Pretenders', 'Pretenders', 'pretenders', 'pretenders'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 84, 'The Smashing Pumpkins', 'Mellon Collie And The Infinite Sadness', 'the smashing pumpkins', 'mellon collie and the infinite sadness'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 85, '2Pac', 'All Eyez On Me', '2pac', 'all eyez on me'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 86, 'Pearl Jam', 'Ten', 'pearl jam', 'ten'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 87, 'Slayer', 'Reign In Blood', 'slayer', 'reign in blood'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 88, 'Alice Coltrane', 'Journey In Satchidananda', 'alice coltrane', 'journey in satchidananda'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 89, 'Green Day', 'Dookie', 'green day', 'dookie'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 90, 'Alanis Morissette', 'Jagged Little Pill', 'alanis morissette', 'jagged little pill'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 91, 'The Who', 'Who''s Next', 'the who', 'who s next'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 92, 'The Replacements', 'Let It Be', 'the replacements', 'let it be'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 93, 'TLC', 'CrazySexyCool', 'tlc', 'crazysexycool'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 94, 'Wilco', 'Yankee Hotel Foxtrot', 'wilco', 'yankee hotel foxtrot'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 95, 'System Of A Down', 'Toxicity', 'system of a down', 'toxicity'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 96, 'N.W.A', 'Straight Outta Compton', 'n w a', 'straight outta compton'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 97, 'Fugazi', 'Repeater', 'fugazi', 'repeater'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 98, 'Lucinda Williams', 'Car Wheels On A Gravel Road', 'lucinda williams', 'car wheels on a gravel road'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 99, 'Kamasi Washington', 'Heaven And Earth', 'kamasi washington', 'heaven and earth'),
('consequence-100', 'Consequence''s 100 Greatest Albums of All Time', 100, 'Jane''s Addiction', 'Nothing''s Shocking', 'jane s addiction', 'nothing s shocking')
on conflict (list_slug, "position") do nothing;
